        self.available_models: Dict[str, Dict[str, Any]] = {
            "mistral": {
                "name": "Mistral-Nemo-Instruct-2407-Q4_K_M.gguf",
                "display_name": "Mistral 7B Nemo Instruct",
                "description": "Einsatzgebiet: Code, technische Details, Systembefehle, schnelle Antworten",
                "context_length": 8192,
                "parameters": "7B",
                "use_case": "code",
                "format": "gguf",
                "size_gb": 7.48,
                "repo_url": "https://huggingface.co/second-state/Mistral-Nemo-Instruct-2407-GGUF",
                "strengths": ["praezise", "strukturiert", "logisch", "schnell", "deutsch-freundlich", "code"],
                "weaknesses": ["weniger kreativ"],
                "role": "technical",
            },
            "deepseek": {
                "name": "deepseek-r1-distill-llama-8b-q4_k_m.gguf",
                "alt_names": [
                    "DeepSeek-R1-Distill-Llama-8B.Q4_K_M.gguf",
                    "DeepSeek-R1-Distill-Llama-8B.Q4_K_S.gguf",
                    "DeepSeek-R1-Distill-Llama-8B.Q5_K_M.gguf",
                    "deepseek-r1-distill-llama-8b.gguf"
                ],
                "display_name": "DeepSeek R1 Distill Llama 8B",
                "description": "Einsatzgebiet: Analysen, komplexe Daten, lange Texte, Reasoning",
                "context_length": 8192,
                "parameters": "8B",
                "use_case": "analysis",
                "format": "gguf",
                "size_gb": 6.9,
                "repo_url": "https://huggingface.co/Triangle104/DeepSeek-R1-Distill-Llama-8B-Q4_K_M-GGUF",
                "strengths": ["hohe rechenleistung", "genauigkeit", "analysen", "reasoning"],
                "weaknesses": ["groesser", "langsamer"],
                "role": "analysis",
            },
            "qwen": {
                "name": "Qwen2.5-7B-Instruct-Q4_K_M.gguf",
                "alt_names": [
                    "Qwen2.5-7B-Instruct-Q4_K_S.gguf",
                    "Qwen2.5-7B-Instruct-Q5_K_M.gguf",
                    "qwen2.5-7b-instruct-q4_k_m.gguf",
                ],
                "display_name": "Qwen 2.5 7B Instruct",
                "description": "Einsatzgebiet: Vielseitig, mehrsprachig, Balance zwischen Geschwindigkeit und Qualitaet",
                "context_length": 32768,
                "parameters": "7B",
                "use_case": "conversation",
                "format": "gguf",
                "size_gb": 5.2,
                "repo_url": "https://huggingface.co/bartowski/Qwen2.5-7B-Instruct-GGUF",
                "strengths": ["vielseitig", "mehrsprachig", "schnell", "balanciert"],
                "weaknesses": ["weniger spezialisiert"],
                "role": "balanced",
            },
            "llama": {
                "name": "llama-2-7b-chat.Q4_K_M.gguf",
                "alt_names": [
                    "llama-2-7b-chat.Q4_K_S.gguf",
                    "llama-2-7b-chat.Q5_K_M.gguf",
                    "Llama-2-7B-Chat-Q4_K_M.gguf",
                    "llama-2-7b.Q4_K_M.gguf",
                ],
                "display_name": "Llama 2 7B Chat",
                "description": "Einsatzgebiet: Unterhaltung, kreative Aufgaben, freundliche Responses",
                "context_length": 4096,
                "parameters": "7B",
                "use_case": "creative",
                "format": "gguf",
                "size_gb": 4.0,
                "repo_url": "https://huggingface.co/TheBloke/Llama-2-7B-Chat-GGUF",
                "strengths": ["kreativ", "freundlich", "konversationell", "kleine groesse"],
                "weaknesses": ["weniger praezise", "begrenzte technische faehigkeiten"],
                "role": "creative",
            },
        }
